In [2]:
import numpy as np

In [3]:
list = [1, 2, 3]
c = np.asarray(list)
# print(c)

In [4]:
c = np.array([1,2,3])
shape = (2,2)
c = np.empty(shape)
d = np.ones(shape)
e = np.zeros(shape)
# print(c,d,e)
# print(shape)

In [5]:
c = np.array([[1.,2.,],[1.,2.]])
d = np.empty_like(c)
# print(d)

In [53]:
a = np.asarray([[1,1,2,3,4],
                [2,6,7,8,9],
                [3,6,7,8,9],
                [4,6,7,8,9],
                [5,6,7,8,9]
               ])
# print(a)
b = np.asarray([[1,1],
                [1,1]])
# print(b)
y = a[:1]
print(y)
y = a[0:1]
print(y)
y = a[3:5]
print(y)
x = a[:, -1]
print(x)
x = a[:3, 0:1]
print(x)
x = a[:4, 1:3]
print(x)

[[1 1 2 3 4]]
[[1 1 2 3 4]]
[[4 6 7 8 9]
 [5 6 7 8 9]]
[4 9 9 9 9]
[[1]
 [2]
 [3]]
[[1 2]
 [6 7]
 [6 7]
 [6 7]]


In [14]:
a3 = np.array([1, 2, 3])
b2 = np.array([5, 6])
print(np.concatenate([a3, b2, b2]))

[1 2 3 5 6 5 6]


In [15]:
a2 = np.array([[1, 2], [3, 4]])
print(np.concatenate((a2, b), axis=0))
print(np.concatenate((a2, b.T), axis=1))

[[1 2]
 [3 4]
 [1 1]
 [1 1]]
[[1 2 1 1]
 [3 4 1 1]]


In [9]:
print(np.append(a, a2))
print(np.append(a, a))

[1 1 2 3 4 2 6 7 8 9 3 6 7 8 9 4 6 7 8 9 5 6 7 8 9 1 2 3 4]
[1 1 2 3 4 2 6 7 8 9 3 6 7 8 9 4 6 7 8 9 5 6 7 8 9 1 1 2 3 4 2 6 7 8 9 3 6
 7 8 9 4 6 7 8 9 5 6 7 8 9]


In [10]:
print(np.append(a2, b, axis=0))
print(np.append(a2, b.T, axis=1))

[[1 2]
 [3 4]
 [1 1]
 [1 1]]
[[1 2 1 1]
 [3 4 1 1]]


In [11]:
print(np.hstack([a2, a2]))

[[1 2 1 2]
 [3 4 3 4]]


In [12]:
print(np.vstack([a2, b2]))

[[1 2]
 [3 4]
 [5 6]]


In [13]:
a = np.array([1, 2, 3.3])
print(a)
print(a.astype(int))

[ 1.   2.   3.3]
[1 2 3]


In [24]:
chararray = np.chararray([3,3], itemsize=3)
chararray[:] = 'abc'
print(chararray)

# intended output?
# >> [['abc' 'abc' 'abc']
#    ['abc' 'abc' 'abc']
#    ['abc' 'abc' 'abc']]

[[b'abc' b'abc' b'abc']
 [b'abc' b'abc' b'abc']
 [b'abc' b'abc' b'abc']]
